# Copyright (C) 2026 Zachary Kenneth Stewart
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

import numpy as np

from chromax import Simulator

class BaseSimulator:
    '''
    Interface for the implementation of a simulation that crosses two parental Genomes,
    according to a GenomeMap, resulting in the production of progeny arrays.
    
    Args:
        genome1 -- a Genome object which is a composition of one or more Chromosome objects,
                   providing an array of parent1's genotypes with shape like: (num_variants, ploidy)
        genome2 -- as above but for the second parent
        genomeMap -- a GenomeMap object which is a composition of ChromosomeMap objects
        seed -- an integer specifying a random seed; default is 1234
    Methods:
        establish -- receives the necessary input data to construct the GenomeMap and Genome
                     of the two parents which will be crossed to generate segregating progeny
        produce_progeny -- makes use of the GenomeMap and Genome of each parent to produce
                           two segregating Populations of progeny
    '''
    def __init__(self, genome1, genome2, genomeMap, seed=1234):
        self.genome1 = genome1
        self.genome2 = genome2
        self.genomeMap = genomeMap
        self.seed = seed
        self.isSimulator = True # object type validator
    
    def cross(self):
        raise NotImplementedError("For implementation by inheriting Class")

class ChromaxSimulator(BaseSimulator):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.numCrosses = 1 # we only simulate a single generation
        self.parents = np.vstack((self.genome1.array, self.genome2.array))
        self.simulator = Simulator(genetic_map=self.genomeMap.df, seed=self.seed)
    
    def cross(self, batchSize=1000):
        '''
        Parameters:
            batchSize -- an integer controlling how many individuals are generated by Chromax at a time.
                         In practice, this serves to reduce the memory consumption of the program by producing
                         progeny iteratively in batches. Default is 1000.
        Returns:
            f1 -- a numpy array with shape: (individuals, variants, ploidy)
        '''
        f1, _ = self.simulator.random_crosses(self.parents, self.numCrosses, n_offspring=batchSize) # f1 has shape (n_crosses, n_individuals, n_loci, n_alleles)
        f1 = f1.reshape(batchSize, len(self.genomeMap.df), self.genome1.ploidy) # reshape to (n_individuals, n_loci, n_alleles)
        f1 = [ np.asarray(x) for x in f1 ] # change type: jaxlib._jax.ArrayImpl -> np.array
        return f1
    
    def __repr__(self):
        return "<ChromaxSimulator object;genomeMap={0};genome1={1};genome2={2}>".format(
            self.genomeMap,
            self.genome1,
            self.genome2
        )
