# Copyright (C) 2026 Zachary Kenneth Stewart
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

import os
import sys

import numpy as np

from chromax import Simulator

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from modules.statistics import RandomNumberGenerator

class BaseSimulator:
    '''
    Interface for the implementation of a simulation that crosses two parental Genomes,
    according to a GenomeMap, resulting in the production of progeny arrays.
    
    Args:
        genome1 -- a Genome object which is a composition of one or more Chromosome objects,
                   providing an array of parent1's genotypes with shape like: (num_variants, ploidy)
        genome2 -- as above but for the second parent
        genomeMap -- a GenomeMap object which is a composition of ChromosomeMap objects
        seed -- an integer specifying a random seed; default is 1234
    Methods:
        establish -- receives the necessary input data to construct the GenomeMap and Genome
                     of the two parents which will be crossed to generate segregating progeny
        produce_progeny -- makes use of the GenomeMap and Genome of each parent to produce
                           two segregating Populations of progeny
    '''
    def __init__(self, genome1, genome2, genomeMap, seed=1234):
        self.genome1 = genome1
        self.genome2 = genome2
        self.genomeMap = genomeMap
        self.seed = seed
        self.isSimulator = True # object type validator
    
    def cross(self, batchSize=1000):
        raise NotImplementedError("For implementation by inheriting Class")

class ChromaxSimulator(BaseSimulator):
    def __init__(self, genome1, genome2, genomeMap, seed=1234):
        super().__init__(genome1, genome2, genomeMap, seed)
        
        self.numCrosses = 1 # we only simulate a single generation
        self.parents = np.vstack((self.genome1.array.reshape(1, *self.genome1.array.shape),
                                  self.genome2.array.reshape(1, *self.genome2.array.shape)))
        self.simulator = Simulator(genetic_map=self.genomeMap.df, seed=self.seed)
        self.isChromaxSimulator = True # object type validator
    
    def cross(self, batchSize=1000):
        '''
        Parameters:
            batchSize -- an integer controlling how many individuals are generated by Chromax at a time.
                         In practice, this serves to reduce the memory consumption of the program by producing
                         progeny iteratively in batches. Default is 1000.
        Returns:
            f1 -- a numpy array with shape: (individuals, variants, ploidy)
        '''
        f1, _ = self.simulator.random_crosses(self.parents, self.numCrosses, n_offspring=batchSize) # f1 has shape (n_crosses, n_individuals, n_loci, n_alleles)
        f1 = f1.reshape(batchSize, len(self.genomeMap.df), self.genome1.ploidy) # reshape to (n_individuals, n_loci, n_alleles)
        f1 = [ np.asarray(x) for x in f1 ] # change type: jaxlib._jax.ArrayImpl -> np.array
        return f1
    
    def __repr__(self):
        return "<ChromaxSimulator object;genomeMap={0};genome1={1};genome2={2}>".format(
            self.genomeMap,
            self.genome1,
            self.genome2
        )

class MeiosisSimulator(BaseSimulator):
    def __init__(self, genome1, genome2, genomeMap, seed=1234, nu=2.5):
        super().__init__(genome1, genome2, genomeMap, seed)
        
        self.nu = nu
        self.parent1 = genome1
        self.parent2 = genome2
        self.rng = RandomNumberGenerator(seed)
        self.isMeiosisSimulator = True # object type validator
    
    @property
    def nu(self):
        return self._nu
    
    @nu.setter
    def nu(self, value):
        try:
            value = float(value)
        except:
            raise ValueError(f"Could not convert '{type(value).__name__}' type object to float")
        if value <= 0:
            raise ValueError(f"nu value must be > zero")
        
        self._nu = value
    
    def _generate_crossovers(self, cmPositions):
        '''
        Parameters:
            cmPositions -- a numpy array of integers giving the centimorgans of each
                           variant position
        Returns:
            crossovers -- a numpy array of float values giving the centimorgans where
                          a crossover should occur
        '''
        cmLength = cmPositions[-1]
        mLength = cmLength / 100.0
        
        crossovers = []
        mPos = 0.0
        while True:
            interval = self.rng.gamma(
                shape=self.nu,
                scale=1.0 / self.nu
            )
            mPos += interval
            if mPos > mLength: # if this position would exceed the actual length of the chromosome
                break
            crossovers.append(mPos * 100.0) # convert back to centimorgans
        
        return np.asarray(crossovers)
    
    def generate_gamete(self, genome):
        '''
        If possible, make this polyploid friendly by swapping out self.rng.integers
        for self.rng.generate_random_indices and other necessary changes.
        There is a chance such changes would be more dramatic and thus require
        popquis to explicitly handle only diploidy.
        
        Parameters:
            genome -- a Genome object for either self.parent1 or self.parent2
        Returns:
            gamete -- a numpy array with shape (variants,) representing a 
        '''
        gamete = []
        for chromosome in genome:
            cmPositions = self.genomeMap[chromosome.chromID].df["cM"].to_numpy()
            
            crossovers = self._generate_crossovers(cmPositions) # cM position where a crossover occurs
            haplotype = self.rng.integers(0, chromosome.ploidy) # randomly choose the starting haplotype
            
            switches = np.searchsorted(
                crossovers,
                cmPositions,
                side="right" # essentially, "round up" to the nearest position
            )
            
            haplotypeChoice = (haplotype + switches) % chromosome.ploidy
            loci = np.arange(chromosome.variants) # should be a better alternative than this?
            
            gamete.append(chromosome.array[loci, haplotypeChoice])
        
        return np.concat(gamete)
    
    def cross(self, batchSize=1000):
        '''
        Parameters:
            batchSize -- an integer controlling how many individuals are generated by Chromax at a time.
                         In practice, this serves to reduce the memory consumption of the program by producing
                         progeny iteratively in batches. Default is 1000.
        Returns:
            f1 -- a numpy array with shape: (individuals, variants, ploidy)
        '''
        f1 = []
        for i in range(batchSize):
            parent1Gamete = self.generate_gamete(self.parent1)
            parent2Gamete = self.generate_gamete(self.parent2)
            offspring = np.column_stack([parent1Gamete, parent2Gamete])
            f1.append(offspring)
        
        return np.asarray(f1)
